name: Build for macOS

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build-mac:
    name: Build for macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build macOS
        run: npm run build-exe

      - name: Create .app and .dmg files
        run: npm run package-mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS-build
          path: release-builds/mac
